name: PR build check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/issue_moderator.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 65

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    outputs:
      individualMatrix: ${{ steps.generate-matrices.outputs.individualMatrix }}
      isIndividualChanged: ${{ steps.parse-changed-files.outputs.isIndividualChanged }}
    env:
      CI_MODULE_GEN: true
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - id: get-changed-files
        name: Get changed files
        uses: Ana06/get-changed-files@v2.2.0

      - id: parse-changed-files
        name: Parse changed files
        run: |
          isIndividualChanged=0
          for changedFile in ${{ steps.get-changed-files.outputs.all }}; do
            if [[ ${changedFile} == src/* ]]; then
              isIndividualChanged=1
            elif [[ ${changedFile} == .github/workflows/issue_moderator.yml ]]; then
              true
            elif [[ ${changedFile} == *.md ]]; then
              true 
            else
              isIndividualChanged=1
              break
            fi
          done
          echo "isIndividualChanged=$isIndividualChanged" >> $GITHUB_OUTPUT

      - name: Get number of modules
        run: |
          set -x

          echo "NUM_INDIVIDUAL_MODULES=$(./gradlew -q projects | grep '.*extensions\:.*\:.*' | wc -l)" >> $GITHUB_ENV

      - id: generate-matrices
        name: Create output matrices
        uses: actions/github-script@v6
        with:
          script: |
            const numIndividualModules = process.env.NUM_INDIVIDUAL_MODULES;
            const chunkSize = process.env.CI_CHUNK_SIZE;

            const numIndividualChunks = Math.ceil(numIndividualModules / chunkSize);

            console.log(`Modules: ${numIndividualModules} (${numIndividualChunks} chunks of ${chunkSize})`);

            core.setOutput('individualMatrix', { 'chunk': [...Array(numIndividualChunks).keys()] });

  build:
    name: Build individual modules
    needs: prepare
    if: ${{ needs.prepare.outputs.isIndividualChanged == '1' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.individualMatrix) }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Build extensions (chunk ${{ matrix.chunk }})
        uses: gradle/gradle-command-action@v2
        env:
          CI_CHUNK_NUM: ${{ matrix.chunk }}
        with:
          arguments: assembleDebug
          cache-read-only: true
